---
title: "编译器错误 CS0156 | Microsoft Docs"
ms.custom: ""
ms.date: "11/17/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "CS0156"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "CS0156"
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
caps.latest.revision: 9
caps.handback.revision: 9
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
translationtype: Human Translation
---
# 编译器错误 CS0156
在嵌套在最近的封闭 catch 子句内部的 finally 子句内不允许使用不带参数的 throw 语句  
  
 不带参数的 [throw](../../csharp/language-reference/keywords/throw.md) 语句只能出现在不带任何参数的 **catch** 子句中。  
  
 有关详细信息，请参阅[异常处理语句](../../csharp/language-reference/keywords/exception-handling-statements.md)和[异常和异常处理](../../csharp/programming-guide/exceptions/exceptions-and-exception-handling.md)。  
  
 下面的示例生成 CS0156：  
  
```  
// CS0156.cs using System; namespace MyNamespace { public class MyClass2 : Exception { } public class MyClass { public static void Main() { try { throw;   // CS0156 } catch(MyClass2) { throw;   // this throw is valid } } } }  
```