---
title: "永远不会到达“Catch”块；&lt;exception&gt; 已在上面同一个“Try”语句中处理 | Microsoft Docs"
ms.custom: ""
ms.date: "11/16/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-visual-basic"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "bc42031"
  - "vbc42031"
helpviewer_keywords: 
  - "BC42031"
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
caps.latest.revision: 10
caps.handback.revision: 10
author: "stevehoag"
ms.author: "shoag"
manager: "wpickett"
translationtype: Human Translation
---
# 永远不会到达“Catch”块；&lt;exception&gt; 已在上面同一个“Try”语句中处理
无法达到代码中的 `Catch` 块，因为它已经在前面的 `Try` 块中得到处理。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参阅 [在 Visual Basic 中配置警告](/visual-studio/ide/configuring-warnings-in-visual-basic)  
  
 **错误 ID：**BC42031  
  
### 更正此错误  
  
-   删除多余的语句。  
  
## 请参阅  
 [如何：在 Visual Basic 中捕获异常](http://msdn.microsoft.com/zh-cn/f3063c89-d2bf-49b1-91b5-b87edfb18b95)   
 [如何：在 Visual Basic 中对具有 Try…Catch 块的代码进行测试](http://msdn.microsoft.com/zh-cn/8368e205-ed73-4185-a247-af84fb4fafa9)   
 [如何：在 Visual Basic 中筛选 Catch 块中的错误](http://msdn.microsoft.com/zh-cn/85964d0a-56e7-4301-a96e-5eaea23b7b9b)   
 [演练：结构化异常处理 \(Visual Basic\)](http://msdn.microsoft.com/zh-cn/440da655-4b32-490b-8b16-bfe46f41fa76)   
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)