---
title: "从未到达“Catch”块，因为“&lt;name1&gt;”从“&lt;name2&gt;”继承。 | Microsoft Docs"
ms.custom: ""
ms.date: "11/16/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-visual-basic"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "BC42029"
  - "vbc42029"
helpviewer_keywords: 
  - "BC42029"
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: 12
caps.handback.revision: 12
author: "stevehoag"
ms.author: "shoag"
manager: "wpickett"
translationtype: Human Translation
---
# 从未到达“Catch”块，因为“&lt;name1&gt;”从“&lt;name2&gt;”继承。
从未到达代码中的 `Catch` 块。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参见 [在 Visual Basic 中配置警告](/visual-studio/ide/configuring-warnings-in-visual-basic)。  
  
 **错误 ID：**BC42029  
  
### 更正此错误  
  
-   删除无关的 `Catch` 块。  
  
## 请参阅  
 [如何：在 Visual Basic 中对具有 Try…Catch 块的代码进行测试](http://msdn.microsoft.com/zh-cn/8368e205-ed73-4185-a247-af84fb4fafa9)   
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)